package presentation.utils

object Strings {
    // actions
    const val ACTIONS = "\n Select an action:\n 1. Catalogs\n 2. Articles\n 3. Finish the job"
    const val SUB_ACTIONS = "\n Select an action:\n 1. Display data from server\n 2. Display parsed data\n 3. Add data\n 3. Delete\n 5. Exit"
    // dialogs
    const val CONFIRM = "Are you sure you want to <do something>? Yes/No"
    const val SEARCH = "Choose which field to search by:"
    const val INDEX = "Enter the index of the record"
    // errors
    const val INDEX_ERROR = "Error: this index doesn't exist"
    const val NULL = "Error: Value is null"
    const val ERROR = "Error: Value is null or incorrect"
    const val INCORRECT_CHOICE = "Error: There is no such choice"
    const val WRONG_CHOICE = "Error: Make the right choice"
    val advices = listOf(
        "https://hramalnevskogo.ru/tpost/cviz4uzje1-pervoe-prichastie-mladentsev-ot-3-4-h-le",
        "https://hramalnevskogo.ru/tpost/1ag8316ja1-prakticheskii-sovet-svyaschennika-kak-pr",
        "https://hramalnevskogo.ru/tpost/xy13y0e331-uchites-bit-schastlivimi",
        "https://hramalnevskogo.ru/tpost/e8j64e6zg1-batyushka-menya-vivodit-iz-sebya-kogda-m",
        "https://hramalnevskogo.ru/tpost/2yhy6v3021-simvol-veri",
        "https://hramalnevskogo.ru/tpost/spb0ia9ml1-o-silnoi-molitve",
        "https://hramalnevskogo.ru/tpost/38g37cx5c1-v-smirenii-est-lyubov",
        "https://hramalnevskogo.ru/tpost/e2rjrlpuu1-vtoraya-zapoved-podobnaya-ei-vozlyubi-bl",
        "https://hramalnevskogo.ru/tpost/ris9tvkg21-bratiya-esli-i-vpadet-chelovek-v-kakoe-s",
        "https://hramalnevskogo.ru/tpost/67dyb6ptr1-prelest",
        "https://hramalnevskogo.ru/tpost/xn6ytmsue1-porozhdeniya-ehidnini-kak-vi-mozhete-gov",
        "https://hramalnevskogo.ru/tpost/fjx9mm7561-pamyatka-voinu",
        "https://hramalnevskogo.ru/tpost/vlo5t73lj1-tot-kto-zhivet-radi-drugih-perestaet-osu",
        "https://hramalnevskogo.ru/tpost/o04neuuc21-po-sotvorenii-cheloveka-gospod-uzhe-ne-d",
        "https://hramalnevskogo.ru/tpost/s40mvittk1-boisya-ne-mislei-svoih-a-zhelanii-ot-mis",
        "https://hramalnevskogo.ru/tpost/h5t4j63zz1-net-nichego-tainogo-chto-ne-sdelalos-bi",
        "https://hramalnevskogo.ru/tpost/f0bftu4ho1-esli-mi-dumaem-o-sebe-horosho-to-mi-v-pr",
        "https://hramalnevskogo.ru/tpost/et95zhn681-lozhas-spat-vspomni-pomog-li-ti-segodnya",
        "https://hramalnevskogo.ru/tpost/3bm35an2b1-nekotorie-govoryat-oi-ya-ne-viderzhu-etu",
        "https://hramalnevskogo.ru/tpost/euvjv44n11-k-pashe-k-voskreseniyu-iz-mertvih-ne-voz",
        "https://hramalnevskogo.ru/tpost/vx9sgdou51-kogda-chelovek-vidit-vokrug-tolko-odnih",
        "https://hramalnevskogo.ru/tpost/u6g3zs9g91-nikakie-krasoti-mira-nikakie-vkusnosti-n",
        "https://hramalnevskogo.ru/tpost/0nyt0mz4s1-k-sozhaleniyu-nas-uzhasaet-ne-gruz-greho",
        "https://hramalnevskogo.ru/tpost/fl80760sv1-est-mnogo-pravoslavnih-kotorie-tolko-naz",
        "https://hramalnevskogo.ru/tpost/vpvp9bk9k1-a-vi-vsegda-obizhaetes-kogda-vas-ne-pobl",
        "https://hramalnevskogo.ru/tpost/vpad2f9d81-mat",
        "https://hramalnevskogo.ru/tpost/yht10mbar1-kogda-zhe-vse-nakonets-poimut-chto-zdes",
        "https://hramalnevskogo.ru/tpost/3730gmzu21-hotite-nauchitsya-molitsya",
        "https://hramalnevskogo.ru/tpost/7k6r6tkku1-vsem-matershinnikam-gospod-popuskaet-sta",
        "https://hramalnevskogo.ru/tpost/f18g5tdnt1-ne-veruyuschii-chelovek-nikogda-ne-smozh",
        "https://hramalnevskogo.ru/tpost/3u8gvx5kf1-deti-horoshie-psihologi-oni-vidyat-vo-vz",
        "https://hramalnevskogo.ru/tpost/3jxgkir2r1-staraites-menshe-govorit-i-menshe-stanet",
        "https://hramalnevskogo.ru/tpost/dmvhsh4891-kogda-sobiraemsya-molitsya-vrag-vnushaet",
        "https://hramalnevskogo.ru/tpost/ssbl0resv1-gospod-ne-narushaya-nashu-svobodnuyu-vol",
        "https://hramalnevskogo.ru/tpost/ut41bs51j1-ne-verte-svoim-usham-verte-svoim-glazam",
        "https://hramalnevskogo.ru/tpost/k9meso8t31-glavnoe-v-nashei-zhizni",
        "https://hramalnevskogo.ru/tpost/ylov5b1y91-vsem-matershinnikam-gospod-popuskaet-sta",
        "https://hramalnevskogo.ru/tpost/52h14yjk11-v-smirenii-est-lyubov",
        "https://hramalnevskogo.ru/tpost/jja7irhjc1-chto-bi-vi-stali-delat-esli-bi-uznali-ch",
        "https://hramalnevskogo.ru/tpost/5ub8oufxl1-vsem-bozhiei-pomoschi-dai-bog-vsem-zdoro",
        "https://hramalnevskogo.ru/tpost/v4oj6b2ym1-pozhaluista-budte-nemnogoslovni"
    )
    val parishLife = listOf(
        "https://hramalnevskogo.ru/tpost/y94h9kv161-hristos-voskrese",
        "https://hramalnevskogo.ru/tpost/a9kfvvy901-v-voskresene-28-aprelya-v-nashem-hrame-s",
        "https://hramalnevskogo.ru/tpost/s7jd5ktfi1-chetverg-5-i-sedmitsi-velikogo-posta-naz",
        "https://hramalnevskogo.ru/tpost/h2c3sbaez1-ves-velikii-post-kazhduyu-subbotu-v-1100",
        "https://hramalnevskogo.ru/tpost/de1rivlk21-blagoe-delo-prisoedinyaites",
        "https://hramalnevskogo.ru/tpost/bxzsuktl41-pervii-den-velikogo-kanona-i-velikogo-po",
        "https://hramalnevskogo.ru/tpost/imojlt0pb1-pervii-den-velikogo-kanona-i-velikogo-po",
        "https://hramalnevskogo.ru/tpost/jzy6yondx1-proschyonnoe-voskresenie",
        "https://hramalnevskogo.ru/tpost/ahjl0h7t31-v-subbotu-16-marta-svyataya-pravoslavnay",
        "https://hramalnevskogo.ru/tpost/20pi4bnvd1-10-marta-na-territorii-nashego-hrama-otp",
        "https://hramalnevskogo.ru/tpost/e4ymvux1x1-nedelya-o-strashnom-sude",
        "https://hramalnevskogo.ru/tpost/i5tpluk4p1-pokayanie-otverzi-mi-dveri",
        "https://hramalnevskogo.ru/tpost/olgopx67l1-7-marta-prazdnuetsya-pamyat-sv-blzh-matr",
        "https://hramalnevskogo.ru/tpost/htbek7a1e1-kazhduyu-subbotu-v-1600-v-nashem-hrame-p",
        "https://hramalnevskogo.ru/tpost/34dodc0fe1-v-nashem-hrame-provodyatsya-zanyatiya-ts",
        "https://hramalnevskogo.ru/tpost/827c1v4ec1-serdechno-blagodarim-narodnii-hor-gusi-l",
        "https://hramalnevskogo.ru/tpost/379elbfmr1-master-klass-po-razrisovivaniyu-pryaniko",
        "https://hramalnevskogo.ru/tpost/0y19n2k3y1-lizhnaya-estafeta-s-prizovimi-nagrazhden",
        "https://hramalnevskogo.ru/tpost/cyc35mt1x1-v-den-rozhdestva-hristova-v-nashem-hrame",
        "https://hramalnevskogo.ru/tpost/a7jh796fa1-vseh-s-prazdnikom-rozhdestva-hristova",
        "https://hramalnevskogo.ru/tpost/vbjitesz31-kazhduyu-subbotu-v-1600-mi-sluzhim-akafi",
        "https://hramalnevskogo.ru/tpost/b2nhy7fi71-u-nas-prestolnii-prazdnik-v-chest-budusc",
        "https://hramalnevskogo.ru/tpost/ied15vr5l1-slava-bogu-nakonets-ikona-prp-aleksandra",
        "https://hramalnevskogo.ru/tpost/k55b1h78a1-venchanie-maksima-i-anni",
        "https://hramalnevskogo.ru/tpost/opde8jfe41-na-prazdnik-prp-sergiya-radonezhskogo-is",
        "https://hramalnevskogo.ru/tpost/fmbbccn5a1-voskresnoe-vsenoschnoe-bdenie-17-i-sedmi",
        "https://hramalnevskogo.ru/tpost/5o29caae71-vozdvizhenie-zhivotvoryaschego-kresta-go",
        "https://hramalnevskogo.ru/tpost/xgxtf13v11-izgotovili-725-okopnih-svechei-dlya-svo",
        "https://hramalnevskogo.ru/tpost/xtlbixtl61-mk-1013-15",
        "https://hramalnevskogo.ru/tpost/yo77xra8t1-pod-vnutrennei-arkoi-nashego-hrama-prp-a",
        "https://hramalnevskogo.ru/tpost/tz7hc9lcg1-u-nas-dvoinoi-prestolnii-prazdnik-v-ches",
        "https://hramalnevskogo.ru/tpost/trh2ya4ny1-segodnya-v-den-useknoveniya-glavi-prorok",
        "https://hramalnevskogo.ru/tpost/cb4ve35461-vsenoschnoe-bdenie-v-chest-prp-aleksandr",
        "https://hramalnevskogo.ru/tpost/zhiojb3691-nedelya-13-ya-po-pyatidesyatnitse",
        "https://hramalnevskogo.ru/tpost/nheom3r6l1-pravoslavnaya-tserkov-prazdnuet-pamyat-p",
        "https://hramalnevskogo.ru/tpost/4mjzutzpd1-vecherom-28-avgusta-v-prazdnik-uspeniya",
        "https://hramalnevskogo.ru/tpost/gclhperub1-prazdnik-uspeniya-presvyatoi-bogoroditsi",
        "https://hramalnevskogo.ru/tpost/0hg2s75451-v-etom-godu-horoshii-urozhai",
        "https://hramalnevskogo.ru/tpost/opdfxzdt11-prazdnik-preobrazheniya-gospodnya",
        "https://hramalnevskogo.ru/tpost/4otljvc391-nedelya-6-ya-po-pyatidesyatnitse",
        "https://hramalnevskogo.ru/tpost/zd5fuc2s51-nedelya-5-ya-po-pyatidesyatnitse",
        "https://hramalnevskogo.ru/tpost/2xo18u2hf1-s-bozhiei-pomoschyu-mi-prodolzhaem-stroi",
        "https://hramalnevskogo.ru/tpost/p181bhg5g1-den-svyatoi-troitsi",
        "https://hramalnevskogo.ru/tpost/a3nu0nl701-ekskursiya-po-donskomu-monastiryu",
        "https://hramalnevskogo.ru/tpost/06k6ck79g1-v-nashem-hrame-troinoi-prazdnik-voskresn",
        "https://hramalnevskogo.ru/tpost/6r8i0g8871-subbota-poslednii-den-svetloi-pashalnoi",
        "https://hramalnevskogo.ru/tpost/1jz4jg9d81-mi-otmetili-pashu-narodnimi-gulyaniyami",
        "https://hramalnevskogo.ru/tpost/2eemdmcp11-hristos-voskrese",
        "https://hramalnevskogo.ru/tpost/5f86r97og1-verbnoe-voskresene",
        "https://hramalnevskogo.ru/tpost/2nr60geah1-chetvertok-velikogo-kanona",
        "https://hramalnevskogo.ru/tpost/4r4koy6sf1-v-trapeznoi-povesili-polki-i-sdelali-bib",
        "https://hramalnevskogo.ru/tpost/csxxch8bz1-liturgiya-prezhdeosvyaschennih-darov",
        "https://hramalnevskogo.ru/tpost/ulbdvp5ph1-ponedelnik-velikogo-kanona",
        "https://hramalnevskogo.ru/tpost/1isrjv3fy1-v-hrame-bila-soveshena-vechernya-s-chino",
        "https://hramalnevskogo.ru/tpost/7yn6bl9c51-v-nashem-hrame-prazdnovalas-maslenitsa",
        "https://hramalnevskogo.ru/tpost/se5r41vb71-partiyu-blindazhnih-svechei-otpravili-vo",
        "https://hramalnevskogo.ru/tpost/d5rs0crot1-dvunadesyatii-prazdnik-sretenya-gospodny",
        "https://hramalnevskogo.ru/tpost/8iy24iep61-kreschenie-gospodne-ili-bogoyavlenie",
        "https://hramalnevskogo.ru/tpost/yz5asg33e1-s-rozhdestvom-hristovim",
        "https://hramalnevskogo.ru/tpost/j03ipfsrn1-buduschii-prestolnii-prazdnik-v-chest-bl",
        "https://hramalnevskogo.ru/tpost/yjncuc2lk1-vozdvizhenie-chestnogo-i-zhivotvoryasche",
        "https://hramalnevskogo.ru/tpost/8i9mv2m691-rozhdestvo-bogoroditsi",
        "https://hramalnevskogo.ru/tpost/jni498t7r1-v-nashem-hrame-bil-dvoinoi-prestolnii-pr",
        "https://hramalnevskogo.ru/tpost/hxe3dy08r1-segodnya-v-nashem-hrame-sostoyalos-pervo",
        "https://hramalnevskogo.ru/tpost/9dx9xkdlu1-hristos-voskrese",
        "https://hramalnevskogo.ru/tpost/6438g03vv1-vseh-s-prazdnikom-vhoda-gospodnya-v-ieru",
        "https://hramalnevskogo.ru/tpost/hyiyjbfyn1-segodnya-sostoyalos-pervoe-soborovanie-v",
        "https://hramalnevskogo.ru/tpost/m9hfcctic1-subbota-vtoroi-sedmitsi-velikogo-posta",
        "https://hramalnevskogo.ru/tpost/bzgsfv6ol1-segodnya-otsluzhili-pervuyu-liturgiyu-pr",
        "https://hramalnevskogo.ru/tpost/b56iy3btl1-vtornik-velikogo-kanona",
        "https://hramalnevskogo.ru/tpost/34fgi2sv61-pervii-den-velikogo-posta",
        "https://hramalnevskogo.ru/tpost/7przz39rb1-zakonchili-potolok",
        "https://hramalnevskogo.ru/tpost/gn5tkrnot1-vseh-s-krescheniem-gospodnim",
        "https://hramalnevskogo.ru/tpost/tlggd33jk1-vtoroi-den-velikogo-posta",
        "https://hramalnevskogo.ru/tpost/29co4gae91-vseh-s-rozhdestvom-hristovim",
        "https://hramalnevskogo.ru/tpost/t2s9zz24i1-s-rozhdestvenskim-sochelnikom",
        "https://hramalnevskogo.ru/tpost/1ztmj7vlc1-otsluzhen-ocherednoi-moleben-s-akafistom",
        "https://hramalnevskogo.ru/tpost/i3rmsofj01-17-noyabrya-2021",
        "https://hramalnevskogo.ru/tpost/tad8h4x321-10-oktyabr-2021",
        "https://hramalnevskogo.ru/tpost/f8n7b73881-29-avgusta-2021",
        "https://hramalnevskogo.ru/tpost/s21169bk91-krestnii-hod-o-skoreishem-postroenii-hra"
    )
    val youthClub = listOf(
        "https://hramalnevskogo.ru/tpost/r1v60e5da1-slyot-pravoslavnoi-molodyozhi-vikariatst",
        "https://hramalnevskogo.ru/tpost/ip6yd07bv1-uchastniki-molodyozhnogo-kluba-ostafevo",
        "https://hramalnevskogo.ru/tpost/5607k45851-voenno-patrioticheskii-slt-pravoslavnoi",
        "https://hramalnevskogo.ru/tpost/vl2hdbfpi1-molodzhnii-klub-prinimaet-aktivnoe-uchas",
        "https://hramalnevskogo.ru/tpost/d3xllnj841-uchastniki-nashego-molodyozhnogo-kluba-p",
        "https://hramalnevskogo.ru/tpost/eppcb6t2p1-26-marta",
        "https://hramalnevskogo.ru/tpost/u9tiasrn61-vnashem-hrame-otkrilsya-molodzhnii-klub",
        "https://hramalnevskogo.ru/tpost/ikk7m0hdc1-prinyali-uchastie-v-patriarshem-bogosluz"
    )
    val history = listOf(
        "https://hramalnevskogo.ru/tpost/651ybe9t11-mi-sdelali-avtomaticheskie-vorota-pri-ve",
        "https://hramalnevskogo.ru/tpost/4cavcythb1-nakonets-sdelali-kupel-dlya-krescheniya",
        "https://hramalnevskogo.ru/tpost/8dbgzaj571-mi-prodolzhaem-delat-kuhnyu-i-kupel-dlya",
        "https://hramalnevskogo.ru/tpost/xcohezat61-slava-bogu-nakonets-ikona-prp-aleksandra",
        "https://hramalnevskogo.ru/tpost/5i7a5ls5y1-stroitelstvo-kuhni",
        "https://hramalnevskogo.ru/tpost/mxae9i5bu1-dorogie-bratya-i-sestri-blagodarya-vashe",
        "https://hramalnevskogo.ru/tpost/isbf7pn0x1-mi-reshili-otkazatsya-ot-zolotogo-elektr",
        "https://hramalnevskogo.ru/tpost/abe5et4zv1-mi-prodolzhaem-stroit-hram-v-chest-prp-a",
        "https://hramalnevskogo.ru/tpost/vk3f6cnjm1-spasibo-vsem-kto-ne-ostalsya-bezuchastni",
        "https://hramalnevskogo.ru/tpost/s5mn08ox31-pervii-den-kak-privezli-stroimaterial-ga",
        "https://hramalnevskogo.ru/tpost/kohjz2op81-privezli-gazobloki",
        "https://hramalnevskogo.ru/tpost/m143iai5k1-segodnya-otsluzhili-moleben-o-postroike",
        "https://hramalnevskogo.ru/tpost/4p79acau81-segodnya-4-aprelya-2022-igumen-alipii-zh",
        "https://hramalnevskogo.ru/tpost/6vn93v4ha1-segodnya-26-dekabrya-2021-goda-sostoyalo",
        "https://hramalnevskogo.ru/tpost/vd1jiuh1p1-zakanchivaem-delat-krishu",
        "https://hramalnevskogo.ru/tpost/a3c8lx1a81-nad-hramom-ustanovlen-kupol-s-krestom",
        "https://hramalnevskogo.ru/tpost/6b72jzps21-segodnya-osobii-znamenatelnii-den",
        "https://hramalnevskogo.ru/tpost/td23h0ydj1-nu-vot-zakonchena-obreshetka-krishi-hram",
        "https://hramalnevskogo.ru/tpost/j4ps0macp1-25092001-vruchenie-ikoni-v-chest-svv-blg",
        "https://hramalnevskogo.ru/tpost/csckslh9y1-29-avgusta-2021",
        "https://hramalnevskogo.ru/tpost/ifdia74ph1-prodolzhaetsya-stroitelstvo-vremennogo-h",
        "https://hramalnevskogo.ru/tpost/216t7yv621-segodnya-kak-i-kazhdoe-voskresenie-bil-o",
        "https://hramalnevskogo.ru/tpost/7ymxy4jz71-vchera-nakonets-s-bozhiei-pomoschyu-podk",
        "https://hramalnevskogo.ru/tpost/srua3plg41-mi-prodolzhaem-stroit",
        "https://hramalnevskogo.ru/tpost/1poig6tik1-kto-znaet-chto-eto-takoe",
        "https://hramalnevskogo.ru/tpost/i85dps1dc1-prodolzhaem-delat-kolodets-na-territorii",
        "https://hramalnevskogo.ru/tpost/2yggotap61-segodnya-18-iyulya-na-territorii-stroite",
        "https://hramalnevskogo.ru/tpost/f3brofhxd1-vchera-razrovnyali-ogromnuyu-ploschadku",
        "https://hramalnevskogo.ru/tpost/0g5x3p98r1-prodolzhaem-delat-fundament-buduschego-h",
        "https://hramalnevskogo.ru/tpost/xbk08szme1-roem-kolodets-dlya-vodi",
        "https://hramalnevskogo.ru/tpost/pfzg08ip71-vo-vremya-zemlyanih-rabot-nashli-pustoi",
        "https://hramalnevskogo.ru/tpost/ypxe1xdib1-hristos-voskrese",
        "https://hramalnevskogo.ru/tpost/voco0ezhy1-hristos-voskrese",
        "https://hramalnevskogo.ru/tpost/8g3074c3s1-23052021",
        "https://hramalnevskogo.ru/tpost/m10sbir5b1-u-nas-na-stroike-hrama-malenkie-radostni",
        "https://hramalnevskogo.ru/tpost/o201c4dhr1-hristos-voskrese"
    )
}